"use client";

import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";

export default function Legal() {
  return (
    <main className="min-h-screen bg-brand-bone">
      <Navbar />
      
      <section className="pt-40 pb-32 px-6">
        <div className="max-w-[1400px] mx-auto flex flex-col space-y-24">
          {/* Header */}
          <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-12 border-b border-brand-charcoal/10 pb-16">
            <div className="flex flex-col space-y-6">
              <div className="text-brand-gold text-[10px] font-black uppercase tracking-[0.4em]">
                Studio Policy
              </div>
              <h1 className="text-5xl lg:text-8xl font-sans font-black text-brand-charcoal uppercase tracking-tighter leading-[0.85]">
                Legal <br />
                <span className="text-brand-charcoal/20 italic font-thin">Structure.</span>
              </h1>
            </div>
            <p className="max-w-md text-brand-charcoal/40 text-sm md:text-base leading-relaxed font-bold uppercase tracking-widest italic text-right">
              Privacy, Terms, and conditions governing the professional relationship between Space Craft and our clients.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-24 font-bold uppercase tracking-[0.15em] text-xs text-brand-charcoal/60 leading-loose">
            <div className="flex flex-col space-y-8">
              <h2 className="text-2xl font-sans font-black text-brand-charcoal tracking-tight">Terms of Engagement</h2>
              <div className="flex flex-col space-y-6">
                <p>1. Every architectural design is subject to site measurements and structural validation by our local engineering team.</p>
                <p>2. Previews generated in the AI Studio are for inspiration only and do not constitute a final construction plan.</p>
                <p>3. Intellectual property of all designs generated by Space Craft remains the exclusive property of the studio.</p>
              </div>
            </div>
            <div className="flex flex-col space-y-8">
              <h2 className="text-2xl font-sans font-black text-brand-charcoal tracking-tight">Privacy Architecture</h2>
              <div className="flex flex-col space-y-6">
                <p>1. Room data uploaded to our AI Design Studio is encrypted and used solely for generating design previews.</p>
                <p>2. We do not store or share your architectural plans with external neural networks except for processing via Google Gemini.</p>
                <p>3. Client data is stored in accordance with applicable data protection laws.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
